services:
  # personalwebsite-backend:
  #   restart: unless-stopped
  #   container_name: personalwebsite-backend
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.backend
  #   env_file: ../.env
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     - NODE_ENV=production
  #   networks:
  #     - personalwebsite-network

  personalwebsite-frontend:
    restart: unless-stopped
    container_name: personalwebsite-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3001"
    networks:
      - personalwebsite-network

networks:
  personalwebsite-network:
    driver: bridge